### ISSUE TITLE
dublicates of links

### ISSUE THREAD

**Issue by iamstarkov** [Connorhd/advanced-navigation#2]
If I use `<link rel="prev" href="…" />` and `<a rel="prev" href="…">prev</a>`  on one page previous links are dublicated though `href` values are the same in both cases/ :
![dublicates of prev links](http://img834.imageshack.us/img834/376/daf784ff73594f819127699.png)

**Comment by iamstarkov** [comment]
is anybody here?

**Comment by Connorhd** [comment]
@matmuchrapna This was just a small project I did to experiment with chrome extensions, I'm not going to be working on it or fixing issues.
